### ISSUE TITLE
Missing uk.ac.leeds.ccg.andyt.generic.memory.Generic_OutOfMemoryErrorHandler

### ISSUE THREAD

**Issue by hupohs** [agdturner/agdt-grids#1]
uk.ac.leeds.ccg.andyt.generic.memory.Generic_OutOfMemoryErrorHandler;
lack of generic package

**Comment by agdturner** [comment]
The generic package is referred to in the Maven pom.xml. You can also pick it up from: https://github.com/agdturner/generic.
